spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp?createDatabaseIfNotExist=true
    username: root
    password: Tanu6601
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    view:
      prefix: /
      suffix: .jsp
      
server:
  port: 9000